#file: noinspection YAMLSchemaValidation
name: Dart

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter --version

      - name: Install dependencies
        run: dart pub get

#      - name: Verify formatting
#        run: dart format --output=none --set-exit-if-changed .

      - uses: invertase/github-action-dart-analyzer@v1