#file: noinspection YAMLSchemaValidation
name: Pull request checks

on:
  push:
    branches: [ 'main', 'develop' ]
  pull_request:
    branches: [ '**' ]

jobs:
  pr_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Install dependencies
        run: dart pub get

      - name: Run codegen
        run: flutter pub run build_runner build

      - name: Run static analyzer
        uses: invertase/github-action-dart-analyzer@v2.0.0
